### ISSUE TITLE
[Bug Report] The Header Image doesn't work

### ISSUE THREAD

**Issue by loctran016** [meteorlxy/vuepress-theme-meteorlxy#92]
## Describe the bug

This is a small bug with the [hearder image](https://vuepress-theme-meteorlxy.meteorlxy.cn/posts/2019/03/23/header-config-en.html#header-image). In dev mode (vuepress dev), the header image work perfectly  but when I deploy to GitLab CI, the header image is blank

## Steps To Reproduce
Here is my [blog](https://loctran016.gitlab.io/notice-blog/)
Here is my [source](https://gitlab.com/LocTran016/notice-blog)

1. Deploy with GitLab with this .gitlab.yml:
```
image: node:14.8.0

before_script:
  - yarn install

pages:
  cache:
    paths:
    - node_modules/

  script:
    - yarn build
  artifacts:
    paths:
    - public
  only:
  - master

lint:
  script:
    - yarn run lint-ci

spellcheck:
  script:
    - yarn run spellcheck

```
2. See error when the website is built

## Screenshots

This is a screenshot when the website is in dev mode
![image](https://user-images.githubusercontent.com/64778285/93008154-beea8d00-f59b-11ea-8783-08b6f3a73fb8.png)

And here is a screenshot of my website
![image](https://user-images.githubusercontent.com/64778285/93008244-be9ec180-f59c-11ea-90f0-f0c78945fcb8.png)
## Expected behavior

The header image work like when it was in dev mode 

## Environment (please complete the following information):

 - Theme Version: [1.9.0]
 - Vuepress Version: [1.5.4]
 - OS: [Window 10 LTSB]
 - Browser: [Brave 1.13.86]
